name: CI

on:
  pull_request:
    branches: ["master","development"]

jobs:
  build-and-test:
    runs-on: ubunto-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: npm install
    